### ISSUE TITLE
HEIC images are rotated

### ISSUE THREAD

**Issue by enricozb** [enricozb/pho-backend#3]
When importing an HEIC/HEIF image, it's rotated when converted to JPEG using `heif-convert`. The reason for this is explained in [this issue](https://github.com/photoprism/photoprism/issues/1064).

It seems like a possible workaround is to roll our own heif-convert.

**Comment by enricozb** [comment]
This also affects the thumbnails of HEIC images as of ac536a6ccd18bc1dbce066af19e363129cd077ae, because thumbnails are generated from the converted images and not the originals.

**Comment by enricozb** [comment]
Solution: Set HEIC converted images to have an orientation of 1, as in [this issue](https://github.com/photoprism/photoprism/issues/1064#issuecomment-783711316).

**Comment by enricozb** [comment]
Fixed in 4c493f80ce5a2c50ac794224e0d2d9fca85fb36b with the above solution.

**Comment by Batwam** [comment]
I have noticed the same issue here with converted files being rotated while the Exif value seems to be as per the original picture. I am having to add `exiftool -n -Orientation=1 file.jpg` after the conversion. Has the solution been implemented? I am using heif-convert 1.12.0

**Comment by enricozb** [comment]
@Batwam I'm not sure if you're commenting on the right repository, this isn't the exiftool repo. I also had to add `-orientation#=1`, and I'm not sure if `exiftool` has fixed this themselves.

**Comment by Batwam** [comment]
@enricozb Apologies, you are right, I was experiencing the a similar issue with heif-convert and got mixed up on the repos!
